version: "3.3"
services:
  app:
    build: app
    restart: always
    ports: 
      - "8006:8006" # List Open ports with process name and pid sudo lsof -i -P -n | grep LISTEN
    environment: 
      ### Salesforce
      aws_acces_key_id: 
      aws_secret_access_key: 
      region_name: 
      sourceEmail: 
      datadog_api_key: 
      datadog_app_key: 
      aws_database_host: 
      aws_database_user: 
      aws_database_pass: 
      aws_db: 
      redis: